### ISSUE TITLE
Name handlers and move them into a separate file. 

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/jquery-ajax-patch#3]
See https://github.com/ga-wdi-boston/planning/issues/5
(Formerly https://github.com/ga-wdi-boston/010/issues/4)

**Comment by jrhorn424** [comment]
I believe this can be closed.

**Comment by gaand** [comment]
I'm not sure that's technically true, but I believe this issue is subsumed by #7, and #8, so I'll close.
